
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #注册驱动
    url: jdbc:mysql://localhost:3306/ems?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: 123456
server:
  servlet:
    context-path: /ems #设置项目名
mybatis:
  mapper-locations: classpath:/mapper/*.xml #Mapper配置文件地址
  type-aliases-package: com.ccb.ems.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl